# Assignment: Create A Multi-Service Multi-Node Web App

## Goal: create networks, volumes, and services for a web-based "cats vs. dogs" voting app
networks:
  frontend:
  backend:
volumes:
  db-data:
services:
  vote:
    image: bretfisher/examplevotingapp_vote
    networks:
      - frontend
    ports:
      - 80:80
    deploy:
      replicas: 2
  redis:
    image: redis:3.2
    networks:
      - frontend
    depends_on:
      - vote
    deploy:
      replicas: 1
  worker:
    image: bretfisher/examplevotingapp_worker
    networks:
      - backend
      - frontend
    depends_on:
      - redis
    deploy:
      replicas: 1
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    depends_on:
      - worker
    deploy:
      replicas: 1
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  result:
    image: bretfisher/examplevotingapp_result
    ports:
      - 5001:80
    networks:
      - backend
    depends_on:
      - db
    deploy:
      replicas: 1

